source 'https://cdn.cocoapods.org/'
# source 'https://github.com/CocoaPods/Specs.git'

flutter_application_path = 'flutter_module/my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

platform :ios, '10.0'

install! 'cocoapods', generate_multiple_pod_projects: true

target 'LearningFlutter' do

pod 'JKCategories'

install_all_flutter_pods(flutter_application_path)

end
